services:
  react:
    build: .
    container_name: mexe-fe
    restart: unless-stopped
    environment:
      - API_URL=http://localhost:3005/api/v1
      - NEXT_PUBLIC_API_URL=http://localhost:3005/api/v1
      - PORT=3000
    ports:
      - "5001:3000"
